apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::650251697076:role/eksctl-roboshop-nodegroup-roboshop-NodeInstanceRole-ptJ0sCvGLN32
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::650251697076:user/suresh
      username: suresh
kind: ConfigMap
metadata:
  creationTimestamp: "2025-08-30T13:30:23Z"
  name: aws-auth
  namespace: kube-system
  uid: 67c7060d-011b-4a47-be50-4859e995c05a
